puppetlabs/puppetlabs-cd4pe

.gitignore, manifests/init.pp, templates/app_env.epp
Prior to this commit, changing the PDB timeout caused the module to add
PUPPET_DB_CONNECTION_TIMEOUT_SEC to the env file for cd4pe.
Unfortunately, this is not the name of the variable the backend code is
looking for, so the setting is never honored.
With this commit, the variable is renamed to
PUPPETDB_CONNECTION_TIMEOUT_SEC to match what the code is looking for at
https://github.com/puppetlabs/PipelinesInfra/blob/3.5.0-release/src/main/java/com/puppet/enterprise/puppetdb/PuppetDBClient.java#L46.  I also updated the internal variable names to match this naming scheme.
I also switch the data type from String to Integer, since it should always be a number.
Testing:
```
[(root@pe-201922-master) ~>]
[(root@pe-201922-master) ~>]
```
```
[(root@pe-201922-agent-cdpe) /etc/puppetlabs/cd4pe>] …
```
=> (CDPE-3131) Align pdb timeout env variable with backend code

test/Dockerfile, test/Makefile, test/README.md, test/configTestVm.sh, test/doConfigTestVm.sh
Create a new container that has all the dependencies -- including the
cdpe-workflow-tests-config.json file -- for running the manual test
automation scripts.
Only the dependencies are built into the container; the scripts
themselves and everything else will be mounted into the container from
the local repository directory.
In order to pull down the private Github repositories specified as
dependencies at runtime your ~/.ssh/id_rsa key will be used.
Since the Ruby Bundler gems have been built into the image, whenever
the Gemfile changes a new image should be built and pushed. A Makefile
with build and push targets has been provided for this.
If desired during development, Docker can be omitted and the
doConfigTestVm.sh script can be executed directly so long as the
dependencies have been …
=> (maint) Run configTestVm.sh from a container

test/Dockerfile, test/README.md, test/configTestVm.sh
Previously we were mounting in and using the entire ~/.ssh/ directory,
which can lead to problems depending on what you have in there when
you run the script.
We only need the SSH key though, so instead just mount in that
individual file instead of the entire directory.
Also add a note to the README about Gemfile.lock causing problems and
how to fix it.
=> (maint) Fix potential SSH issues and add Gemfile.lock note

lib/puppet/functions/cd4pe/compiling_server_osfamily.rb, manifests/init.pp
Prior to this commit, it was possible to attempt an installation of
cd4pe on an agent with a different OS release than the PE master.  This
installation attempt would fail, generally looking for postgresql
packages with an error that would likely not lead a user to suspect the
actual cause of the problem.
With this commit, we will now compare the OS family to make sure they
are the same before continuing.
Tested by running with RHEL agent against a RHEL master, and the run
completed successfully.  With an Ubuntu agent against the same RHEL
master, you get an immediate failure:
```
Info: Using configured environment 'production'
Info: Retrieving pluginfacts
Info: Retrieving plugin
Info: Retrieving locales
Info: Loading facts
Error: Could not retrieve catalog from remote server: Error 500 …
```
=> (CDPE-3231) Add OS family check for cd4pe installation

lib/puppet/functions/cd4pe/compiling_server_osfamily.rb, manifests/init.pp
Reverts puppetlabs/puppetlabs-cd4pe#83
Reverting for now as it's breaking CI, and i'm extra concerned by your comment on the PR that i didn't see before merging
> I was able to successfully install CD4PE on an Ubuntu 16.04 agent from an 18.04 master.
This should not be possible, and 100% is not something we should continue to support.
=> Revert "(CDPE-3231) Add OS family check for cd4pe installation"

metadata.json
The pipeline modules dependency creates conflicting version dependencies that cannot be resolved.  Instead of updating the dependencies of the pipelines module it seems reasonable to remove the dependency altogether as it was used for optional functionality and is also no longer needed with the addition of puppet agent based job hardware.
=> (CDPE-3234) Remove pipelines dependency

Rakefile, lib/puppet/functions/cd4pe/compiling_server_operatingsystemmajrelease.rb, lib/puppet/functions/cd4pe/compiling_server_osfamily.rb, manifests/init.pp
Prior to this commit, it was possible to attempt an installation of
cd4pe on an agent with a different OS release than the PE master.  This
installation attempt would fail, generally looking for postgresql
packages with an error that would likely not lead a user to suspect the
actual cause of the problem.
With this commit, we will now compare the OS family and major release 
to make sure they are the same before continuing.
I also update the Rakefile to do a facter override of the facts during testing.
Without this change, the test would think the PE Master was "Darwin", since it was
running on my mac desktop, and fail.  Overriding the fact to RedHat solves this, since
we also hardcode the agent as a centos-7 box.
Tests:
`CD4PE_IMAGE=artifactory.delivery.puppetlabs.net/cd4pe-dev …
=> (CDPE-3231) Add OS family check for cd4pe installation with test update

.fixtures.yml
Previous to this commit, the fixtures file was pulling #master for all
the modules we use. This could lead to tests failing if #master of a
module repo is broken.
This commit changes it to use forge for all modules that are published
to the forge. There are still a handful of PE specific ones / helpers
that are internal only and not published to the forge. Those are left to
#master for now.
=> (maint) Use forge for fixtures

Gemfile
Previous to this commit, we were pulling in the latest facter gem.
However that was leading to failures in CI as it was causing catalog
compilation failures with 4.x, and no useful debug logging at the time
to figure out why.
For now, pin to 2.x to get CI working again while we investigate the
root cause to remove this pinning.
=> (maint) Pin to facter 2.x

lib/puppet_x/puppetlabs/cd4pe_client.rb, tasks/discover_pe_credentials.json, tasks/discover_pe_credentials.rb
This PR fixes a problem with the `cd4pe::discover_pe_credentials` task, as the original task would cause the PE token to only be valid for 1 hour. With this PR:
* The default value for a new token, if unspecified, is 180 days (`180d`)
* The discover_pe_credentials gets a new `token_lifetime` optional parameter that allows the user to specify a custom lifetime
=> Enable token lifetime param in discover_pe_credentials task

manifests/init.pp
The new query service listens on port 8888.  Currently this is
fixed and cannot be changed.
This change exposes port 8888 via docker port bindings.
=> (LIDAR-259) Expose Port Used for Query Service

CHANGELOG.md, metadata.json
This change bumps the metadata version to 2.0.0 and adds a short list of changes made in this new version to the CHANGELOG. I wasn't going to sort through the entire commit diff but I think I caught the important stuff.c
=> CDPE-2928 Bump metadata to 2.0.0 and update CHANGELOG

.fixtures.yml
- Update the ref to the pe_xl module so that it uses the proper branch
name as a consequence of moving away from using "master" terminology.
- Without this change we can't pull down the fixtures because the master
branch no longer exists on the pe_xl module.
=> (maint) Update the fixtures yaml to reflect the branch change on the pe_xl module

lib/puppet/functions/cd4pe/compiling_server_osfamily.rb, lib/puppet/functions/cd4pe/compiling_server_osname.rb, manifests/init.pp
I encountered this error message in our environment with Ubuntu:
```Error while evaluating a Function Call, The PE Master OS 'Debian 16.04' must match the cd4pe agent node OS 'Debian 18.04'```
I think OS family paints with too broad of a brush for some OSes and OS name gives a more accurate error:
```Error while evaluating a Function Call, The PE Master OS 'Ubuntu 16.04' must match the cd4pe agent node OS 'Ubuntu 18.04'```
=> Changes OS check to use name instead of family

.fixtures.yml
There is currently a bug with the 3.11.0 released version of docker
that is causing the network flags to be added improperly. I'm unsure if
this is due to our usages of it, or the PR number 647 on the docker
module.
The change was causing the docker create command to be passed two
network flags, one called bridge, and one called cd4pe.
This commit pins us to the last known good version will we investigate
and work with the IA content team to understand if it's our usage, or a
bad change.
=> (maint) Pin docker fixture to 3.10.2

CHANGELOG.md, metadata.json
- Since the Puppet platform now has support for RHEL/CentOS 8.1 and 8.2
we're updating the supported OS list of the module.
- Since we'll be performing a 3.0.2 release with the updated OS list I've included the commit for the release prep here.
=> (CDPE-3919) Add el 8 to supported OS list and 3.0.2 release prep

manifests/db/postgres.pp
`puppet_enterprise::pg::cert_whitelist_entry` was renamed to `puppet_enterprise::pg::cert_allowlist_entry`. Using the old function name results in deprecation messages getting reported to our users. This change fixes that.
=> Use new cert_allowlist_entry function name

.fixtures.yml
puppetlabs/provision no longer has a master branch, only main, and puppetlabs/enterprise_tasks still has a 'master' but now also has a 'main' so we should probably just get ahead of it. the provision branch issue is causing CI failures
=> (maint) Update fixture refs to 'main' from 'master'

lib/puppet_x/puppetlabs/cd4pe_client.rb
Prior to this change, if the web_ui_endpoint supplied by CD4PE contained
a path after the port, we ignored it and simply attempted to hit the
server/port. This historically worked just fine, as CD4PE never
specified a path after the port; however, in CD4PE 4.5.0, we introduced
a path prefix that all traffic to CD4PE has to respect.
With this change, we add logic to respect the URI path if one exists,
allowing us to use the puppetlabs-cd4pe module with CD4PE 4.5.0+.
=> (CDPE-4193) Respect uri path when hitting cd4pe backend

lib/puppet_x/puppetlabs/cd4pe_client.rb, tasks/promote_repo_to_stage.json, tasks/promote_repo_to_stage.rb
The `promote_pipeline_to_stage` task can be used for - you guessed it - promoting a pipeline.
For that task to work, a method `promote_pipeline_to_stage` has been added to the client.
Note that no unit tests have been added yet because some of the current unit tests are failing - happy to add after some guidance on whether the existing unit tests should be fixed as well.
=> Add promote_pipeline_to_stage task and client method

lib/puppet_x/puppetlabs/cd4pe_client.rb, tasks/promote_pipeline_to_stage.json, tasks/promote_pipeline_to_stage.rb
1. The task was erroneously named `promote_repo_to_stage`, fixed that by renaming to the intended name `promote_pipeline_to_stage`
2. Added the `commit_sha` parameter to enable important use cases which need to promote a specific commit
=> Rename task to promote_pipeline_to_stage; add sha parameter

CHANGELOG.md, lib/puppet_x/puppetlabs/cd4pe_client.rb
This PR fixes the following error when trying to use Tasks in v3.2.1 of the module against a CD4PE 3.x HTTP endpoint:
```
Error: Finished with exit code 1
{:_error=>{:msg=>"Task failed: SSL_connect returned=1 errno=0 state=error: wrong version number", :kind=>"puppetlabs-cd4pe/promote_pipeline_to_stage_error", :details=>"OpenSSL::SSL::SSLError"}}
```
It allows customers using both CD4PE 3.x and 4.x to leverage the a single version of the CD4PE module for executing Tasks against either instance.
=> Properly handle non-SSL endpoints for CD4PE 3.x

.pdkignore, CHANGELOG.md, README.md, RELEASE.md, tasks/add_deployment_to_stage.rb, tasks/add_job_to_stage.rb, tasks/add_oauth_integration.rb, tasks/add_pr_gate_to_stage.rb, tasks/add_repo.rb, tasks/add_vcs_integration.rb, tasks/create_pipeline.rb, tasks/create_user.rb, tasks/create_workspace.rb, tasks/discover_pe_credentials.rb, tasks/promote_pipeline_to_stage.rb
This PR contains two commits.
The first updates the default for the web_ui_endpoint to add /cd4pe onto the end of the path, as required by teams ui. This only changes the default behavior if the user does not supply the param themself, so as not to break users who have already updated it accordingly on their own.
The second removes the release instructions from the readme and moves them into a separate markdown file so that they won't be publicly exposed on the forge.
=> (CDPE-4881) Update default for web_ui_endpoint

.github/workflows/release.yml, .sync.yml, metadata.json
This commit adds a github action based module release pipeline through adding a release workflow to the .sync.yml file as well as a corresponding github workflow release yaml. It also changes the project author in the metadata.json to match the github namespace ('puppetlabs').
=> (maint) add release pipeline

CHANGELOG.md, RELEASE.md
This PR updates RELEASE.md to use the new publish module github action for pushing changes to the forge, rather than directing devs to build locally and manually push to the forge by logging in with the shared credentials.
It also has a second commit to fix an error in the changelog for version 3.2.3, where the changelog didn't reflect the new version format (vX.Y.Z rather than X.Y.Z), causing a dead link.
=> (maint) update release instructions for new publish action and fix v3.2.3 changelog

lib/puppet_x/puppetlabs/cd4pe_client.rb
Previously the generic error handler that'd catch all non-401 error states when the client was setting the auth cookie would swallow the error response and instead return an error about invalid login credentials. However this was misleading as invalid credentials would result in a 401, and the handler was catching all error responses except 401s. This adjusts it to instead return the error status and body.
=> (CDPE-4883) clarify generic login error response

tasks/add_repo.rb
When the optional parameter `pipelines_as_code_branch` is not supplied,
the type of `pipelines_as_code_branch` is `nil`, which has no `.empty?`.
Instead, just test whether it's a `nil`.
=> [CDPE-4886] accept empty pipelines branch

metadata.json
The following updates increment the module versions to support Puppet 8. Running this set on a CD4PE 5.3.2 install against a 2021.7.0 PE ran without problems. Tested job runs on job hardware provisioned using the docker module and deployments. Running `puppet module list` on the PE server afterwards showed no module incompatibilities. 
For testing, I used a Puppetfile of:
```
mod 'cd4pe',
:git => 'https://github.com/puppetlabs/puppetlabs-cd4pe.git',
:branch => 'cdpe-6453/update-versions-for-puppet8'
mod 'puppetlabs-cd4pe_jobs', '1.6.3'
mod 'puppetlabs-concat', '9.0.2'
mod 'puppetlabs-hocon', '1.1.0'
mod 'puppetlabs-puppet_authorization', '1.0.0'
mod 'puppetlabs-stdlib', '9.6.0'
mod 'puppetlabs-docker', '9.1.0'
mod 'puppetlabs-apt', '9.4.0'
mod 'puppetlabs-translate', '1.1.0'
mod …
```
=> (CDPE-6453) Update module versions for Puppet 8 support
